version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-dev-axemig_server_1
      APP_PORT: 12150

  server:
    image: ghcr.io/willitmod/axemig:0.1.8
    restart: on-failure
    stop_grace_period: 30s
    init: true
    environment:
      AXEMIG_HOME: /data
      AXEMIG_PORT: 12150
      AXEMIG_HOST: 0.0.0.0
      AXEMIG_HELPER_IMAGE: ghcr.io/willitmod/axemig:0.1.8
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
